### ISSUE TITLE
caldav request cannot be processed

### ISSUE THREAD

**Issue by Cominch** [quiqueck/homebridge-daily-sensors#12]
TypeError: Cannot read property 'deb' of undefined
    at /usr/local/lib/node_modules/homebridge-daily-sensors/lib/web.js:238:26
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-daily-sensors/node_modules/express/lib/router/layer.js:95:5)

**Comment by Cominch** [comment]
This is just a typo in the line mentioned above (log.debug)
